In [2]:
from build_df import build_dataframe
from analyze_files import build_folder_summary

df_meta = build_dataframe()

df_meta

Number of .txt files found:  2540

,source_path,temp_folder_label,deltaT_label,T_plate_label,series_id,channel_raw,channel_norm,pressure_raw_label,pressure_corr_mpa,point_type,pair_id,role,is_complete_pair,reference_zero_id
0,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
1,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
2,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
3,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
4,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,DT0_T23_15,0.0,23,15,CH1,Y,0.5MPa,0.5,pressure_point,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,EDA;pressure_calibration;joint_regression;,True,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2535,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2536,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2537,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2538,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...
2539,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,DT45.7_T75_27,45.7,75,27,CH2,X,9MPa,9.0,pressure_point,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,EDA;joint_regression;,True,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...

In [3]:
df_summary = build_folder_summary(df_meta)

df_summary

Building summary: 100%|██████████| 1270/1270 [00:34<00:00, 36.36it/s]

,folder,pressure,dT,Tp,y_signal,x_signal,role,path_y,path_x,ref,low_quality,y_quality,y_quality_ref,x_quality,x_quality_ref
0,DT0_T23_15,0.5,0.0,23,-1.140635,0.195342,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.993451,1.000000,0.994875,0.995729
1,DT0_T23_15,0.5,0.0,23,-1.103324,0.183002,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.982346,0.998576,0.990319,0.995444
2,DT0_T23_15,0.5,0.0,23,-1.132613,0.193438,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.987472,0.999146,0.993736,0.997153
3,DT0_T23_15,0.5,0.0,23,-1.120898,0.208898,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.984339,0.999715,0.992312,0.997153
4,DT0_T23_15,0.5,0.0,23,-1.115012,0.199869,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.985478,0.999146,0.992597,0.995729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,DT45.7_T75_27,9.0,45.7,75,-17.393602,6.353061,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.990037
1176,DT45.7_T75_27,9.0,45.7,75,-17.392781,6.335698,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.989752
1177,DT45.7_T75_27,9.0,45.7,75,-17.387492,6.334266,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.989752
1178,DT45.7_T75_27,9.0,45.7,75,-17.357476,6.360441,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989752,0.990037
1179,DT45.7_T75_27,9.0,45.7,75,-17.375052,6.322131,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.990037

In [4]:
df_summary.isnull().sum()

folder           0
pressure         0
dT               0
Tp               0
y_signal         0
x_signal         0
role             0
path_y           0
path_x           0
ref              0
low_quality      0
y_quality        0
y_quality_ref    0
x_quality        0
x_quality_ref    0
dtype: int64

In [5]:
df_summary[df_summary["ref"].notna()]

,folder,pressure,dT,Tp,y_signal,x_signal,role,path_y,path_x,ref,low_quality,y_quality,y_quality_ref,x_quality,x_quality_ref
0,DT0_T23_15,0.5,0.0,23,-1.140635,0.195342,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.993451,1.000000,0.994875,0.995729
1,DT0_T23_15,0.5,0.0,23,-1.103324,0.183002,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.982346,0.998576,0.990319,0.995444
2,DT0_T23_15,0.5,0.0,23,-1.132613,0.193438,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.987472,0.999146,0.993736,0.997153
3,DT0_T23_15,0.5,0.0,23,-1.120898,0.208898,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.984339,0.999715,0.992312,0.997153
4,DT0_T23_15,0.5,0.0,23,-1.115012,0.199869,EDA;pressure_calibration;joint_regression;,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channe...,PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channe...,False,0.985478,0.999146,0.992597,0.995729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,DT45.7_T75_27,9.0,45.7,75,-17.393602,6.353061,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.990037
1176,DT45.7_T75_27,9.0,45.7,75,-17.392781,6.335698,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.989752
1177,DT45.7_T75_27,9.0,45.7,75,-17.387492,6.334266,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.989752
1178,DT45.7_T75_27,9.0,45.7,75,-17.357476,6.360441,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989752,0.990037
1179,DT45.7_T75_27,9.0,45.7,75,-17.375052,6.322131,EDA;joint_regression;,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_cha...,PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_cha...,False,1.000000,1.000000,0.989468,0.990037

In [6]:
df_base_for_training = df_summary[df_summary["ref"].notna()][["pressure", "dT", "Tp", "y_signal", "x_signal", "role", "low_quality", "x_quality", "x_quality_ref", "y_quality", "y_quality_ref"]]
df_base_for_training[df_base_for_training["x_quality"] > 0.9]

,pressure,dT,Tp,y_signal,x_signal,role,low_quality,x_quality,x_quality_ref,y_quality,y_quality_ref
0,0.5,0.0,23,-1.140635,0.195342,EDA;pressure_calibration;joint_regression;,False,0.994875,0.995729,0.993451,1.000000
1,0.5,0.0,23,-1.103324,0.183002,EDA;pressure_calibration;joint_regression;,False,0.990319,0.995444,0.982346,0.998576
2,0.5,0.0,23,-1.132613,0.193438,EDA;pressure_calibration;joint_regression;,False,0.993736,0.997153,0.987472,0.999146
3,0.5,0.0,23,-1.120898,0.208898,EDA;pressure_calibration;joint_regression;,False,0.992312,0.997153,0.984339,0.999715
4,0.5,0.0,23,-1.115012,0.199869,EDA;pressure_calibration;joint_regression;,False,0.992597,0.995729,0.985478,0.999146
...,...,...,...,...,...,...,...,...,...,...,...
1175,9.0,45.7,75,-17.393602,6.353061,EDA;joint_regression;,False,0.989468,0.990037,1.000000,1.000000
1176,9.0,45.7,75,-17.392781,6.335698,EDA;joint_regression;,False,0.989468,0.989752,1.000000,1.000000
1177,9.0,45.7,75,-17.387492,6.334266,EDA;joint_regression;,False,0.989468,0.989752,1.000000,1.000000
1178,9.0,45.7,75,-17.357476,6.360441,EDA;joint_regression;,False,0.989752,0.990037,1.000000,1.000000
1179,9.0,45.7,75,-17.375052,6.322131,EDA;joint_regression;,False,0.989468,0.990037,1.000000,1.000000

In [19]:
from utils import quality_report


print(quality_report(df_base_for_training, 0.9))

total                     1180
low_quality_original       107
low_quality_recomputed     107
x_good                    1142
x_ref_good                1180
y_good                    1179
y_ref_good                1103
all_good                  1073
dtype: int64

In [8]:
df_base_for_training[df_base_for_training["role"].str.contains("EDA")].info()

<class 'pandas.DataFrame'>
RangeIndex: 1180 entries, 0 to 1179
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       1180 non-null   float64
 1   dT             1180 non-null   float64
 2   Tp             1180 non-null   int64
 3   y_signal       1180 non-null   float64
 4   x_signal       1180 non-null   float64
 5   role           1180 non-null   str
 6   low_quality    1180 non-null   bool
 7   x_quality      1180 non-null   float64
 8   x_quality_ref  1180 non-null   float64
 9   y_quality      1180 non-null   float64
 10  y_quality_ref  1180 non-null   float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 93.5 KB

In [9]:
df_base_for_training[df_base_for_training["role"].str.contains("joint_regression")].info()

<class 'pandas.DataFrame'>
RangeIndex: 1180 entries, 0 to 1179
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       1180 non-null   float64
 1   dT             1180 non-null   float64
 2   Tp             1180 non-null   int64
 3   y_signal       1180 non-null   float64
 4   x_signal       1180 non-null   float64
 5   role           1180 non-null   str
 6   low_quality    1180 non-null   bool
 7   x_quality      1180 non-null   float64
 8   x_quality_ref  1180 non-null   float64
 9   y_quality      1180 non-null   float64
 10  y_quality_ref  1180 non-null   float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 93.5 KB

In [10]:

df_base_for_training[df_base_for_training["role"].str.contains("pressure_calibration")].info()

<class 'pandas.DataFrame'>
Index: 110 entries, 0 to 119
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       110 non-null    float64
 1   dT             110 non-null    float64
 2   Tp             110 non-null    int64
 3   y_signal       110 non-null    float64
 4   x_signal       110 non-null    float64
 5   role           110 non-null    str
 6   low_quality    110 non-null    bool
 7   x_quality      110 non-null    float64
 8   x_quality_ref  110 non-null    float64
 9   y_quality      110 non-null    float64
 10  y_quality_ref  110 non-null    float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 9.6 KB

In [11]:

df_base_for_training[df_base_for_training["role"].str.contains("repeatability_test")].info()

<class 'pandas.DataFrame'>
Index: 60 entries, 20 to 1089
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pressure       60 non-null     float64
 1   dT             60 non-null     float64
 2   Tp             60 non-null     int64
 3   y_signal       60 non-null     float64
 4   x_signal       60 non-null     float64
 5   role           60 non-null     str
 6   low_quality    60 non-null     bool
 7   x_quality      60 non-null     float64
 8   x_quality_ref  60 non-null     float64
 9   y_quality      60 non-null     float64
 10  y_quality_ref  60 non-null     float64
dtypes: bool(1), float64(8), int64(1), str(1)
memory usage: 5.2 KB