In [2]:
import pandas as pd
from build_df import build_dataframe
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

# Load and display DataFrame
df = build_dataframe()
df

Number of .txt files found:  2540

                                                          source_path temp_folder_label  deltaT_label  T_plate_label series_id channel_raw channel_norm pressure_raw_label  pressure_corr_mpa      point_type                                                          pair_id  is_complete_pair                                                reference_zero_id  is_temp_calibration  is_pressure_calibration  is_joint_regression  is_repeatability_test
0      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-1.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-1.txt              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-1.txt                False                     True                 True                  False
1     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-10.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point  PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-10.txt              True    PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-10.txt                False                     True                 True                  False
2      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-2.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-2.txt              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-2.txt                False                     True                 True                  False
3      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-3.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-3.txt              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-3.txt                False                     True                 True                  False
4      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-4.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-4.txt              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-4.txt                False                     True                 True                  False
...                                                               ...               ...           ...            ...       ...         ...          ...                ...                ...             ...                                                              ...               ...                                                              ...                  ...                      ...                  ...                    ...
2535  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-5.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-5.txt              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-5.txt                False                    False                 True                  False
2536  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-6.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-6.txt              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-6.txt                False                    False                 True                  False
2537  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-7.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-7.txt              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-7.txt                False                    False                 True                  False
2538  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-8.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-8.txt              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-8.txt                False                    False                 True                  False
2539  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-9.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-9.txt              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-9.txt                False                    False                 True                  False

[2540 rows x 17 columns]

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540 entries, 0 to 2539
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   source_path              2540 non-null   str
 1   temp_folder_label        2540 non-null   str
 2   deltaT_label             2540 non-null   float64
 3   T_plate_label            2540 non-null   int64
 4   series_id                2540 non-null   str
 5   channel_raw              2540 non-null   str
 6   channel_norm             2540 non-null   str
 7   pressure_raw_label       2540 non-null   str
 8   pressure_corr_mpa        2540 non-null   float64
 9   point_type               2540 non-null   str
 10  pair_id                  2540 non-null   str
 11  is_complete_pair         2540 non-null   bool
 12  reference_zero_id        2540 non-null   str
 13  is_temp_calibration      2540 non-null   bool
 14  is_pressure_calibration  2540 non-null   bool
 15  is_joint_regression      2540 non-null   bool
 16  is_repeatability_test    2540 non-null   bool
dtypes: bool(5), float64(2), int64(1), str(9)
memory usage: 250.7 KB

In [4]:
df.isnull().sum()

source_path                0
temp_folder_label          0
deltaT_label               0
T_plate_label              0
series_id                  0
channel_raw                0
channel_norm               0
pressure_raw_label         0
pressure_corr_mpa          0
point_type                 0
pair_id                    0
is_complete_pair           0
reference_zero_id          0
is_temp_calibration        0
is_pressure_calibration    0
is_joint_regression        0
is_repeatability_test      0
dtype: int64

In [5]:
df["deltaT_label"].unique()

array([ 0. , 16.2, 20.5, 24.7, 27.4, 33. , 37.5, 41.8, 45.7])

In [6]:
df["T_plate_label"].unique()

array([23, 42, 45, 50, 55, 60, 65, 70, 75])

In [ ]:
df["pressure_corr_mpa"].value_counts()

np.int64(2540)

In [8]:
df["pressure_raw_label"].unique()

<StringArray>
[ '0.5MPa',    '0MPa',   '10MPa',   '11MPa',    '1MPa',    '2MPa',    '3MPa',
    '4MPa',    '5MPa',    '6MPa',    '7MPa',    '8MPa',    '9MPa',  '0.1MPa',
  '0.2MPa', '0.01MPa']
Length: 16, dtype: str

In [9]:
df["role"].unique()

KeyError: 'role'

In [ ]:
df["point_type"].unique()

<StringArray>
['pressure_point', 'zero_start', 'zero_end']
Length: 3, dtype: str

In [ ]:
df["is_complete_pair"].unique()

array([ True])

In [ ]:
db = pd.read_csv("Output_files/paired_features.csv")
db

      series_id  pressure    dT  Tp       mu_Y       mu_X     std_Y     std_X     irq_Y     irq_X  is_temp_calibration  is_pressure_calibration  is_joint_regression  is_repeatability_test  low_quality
0            15       0.5   0.0  23  -1.161463   0.177174  0.148690  0.080380  0.208516  0.103947                False                     True                 True                  False        False
1            15       0.5   0.0  23  -1.134390   0.160566  0.142894  0.082127  0.211629  0.107682                False                     True                 True                  False        False
2            15       0.5   0.0  23  -1.149027   0.174392  0.144446  0.078795  0.204315  0.100057                False                     True                 True                  False        False
3            15       0.5   0.0  23  -1.142649   0.179321  0.144685  0.080948  0.201047  0.102702                False                     True                 True                  False        False
4            15       0.5   0.0  23  -1.140869   0.169717  0.146148  0.080401  0.217230  0.102702                False                     True                 True                  False        False
...         ...       ...   ...  ..        ...        ...       ...       ...       ...       ...                  ...                      ...                  ...                    ...          ...
1265         27       9.0  45.7  75 -82.669577 -59.543071  1.117709  1.085852  2.134331  2.233070                False                    False                 True                  False        False
1266         27       9.0  45.7  75 -82.685232 -59.550092  1.124685  1.084317  2.148346  2.237428                False                    False                 True                  False        False
1267         27       9.0  45.7  75 -82.669424 -59.548976  1.122806  1.083446  2.139313  2.226298                False                    False                 True                  False        False
1268         27       9.0  45.7  75 -82.656679 -59.529346  1.123449  1.085689  2.144920  2.235169                False                    False                 True                  False        False
1269         27       9.0  45.7  75 -82.662247 -59.548707  1.119223  1.087563  2.117844  2.239214                False                    False                 True                  False        False

[1270 rows x 15 columns]

In [ ]:
db["series_id"].unique()

array([15,  2, 19, 20, 16, 21, 25, 26, 27])

In [ ]:
(db[db["Tp"] == 23]["is_pressure_calibration"])

0      True
1      True
2      True
3      True
4      True
       ...
125    True
126    True
127    True
128    True
129    True
Name: is_pressure_calibration, Length: 130, dtype: bool

In [ ]:
db[db["dT"] == 0]

     series_id  pressure   dT  Tp       mu_Y      mu_X     std_Y     std_X     irq_Y     irq_X  is_temp_calibration  is_pressure_calibration  is_joint_regression  is_repeatability_test  low_quality
0           15       0.5  0.0  23  -1.161463  0.177174  0.148690  0.080380  0.208516  0.103947                False                     True                 True                  False        False
1           15       0.5  0.0  23  -1.134390  0.160566  0.142894  0.082127  0.211629  0.107682                False                     True                 True                  False        False
2           15       0.5  0.0  23  -1.149027  0.174392  0.144446  0.078795  0.204315  0.100057                False                     True                 True                  False        False
3           15       0.5  0.0  23  -1.142649  0.179321  0.144685  0.080948  0.201047  0.102702                False                     True                 True                  False        False
4           15       0.5  0.0  23  -1.140869  0.169717  0.146148  0.080401  0.217230  0.102702                False                     True                 True                  False        False
..         ...       ...  ...  ..        ...       ...       ...       ...       ...       ...                  ...                      ...                  ...                    ...          ...
125         15       9.0  0.0  23 -17.755096  6.391227  0.325054  0.143641  0.390890  0.196067                False                     True                 True                  False        False
126         15       9.0  0.0  23 -17.756472  6.396956  0.323646  0.140836  0.383112  0.184864                False                     True                 True                  False        False
127         15       9.0  0.0  23 -17.731649  6.391430  0.333057  0.141537  0.382331  0.196067                False                     True                 True                  False        False
128         15       9.0  0.0  23 -17.748978  6.409171  0.334954  0.144504  0.400227  0.197935                False                     True                 True                  False        False
129         15       9.0  0.0  23 -17.763921  6.400824  0.323325  0.142608  0.390268  0.196067                False                     True                 True                  False        False

[130 rows x 15 columns]