In [1]:
import pandas as pd
from build_df import build_dataframe
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
pd.set_option("display.expand_frame_repr", False)

# Load and display DataFrame
df = build_dataframe()
df

Number of .txt files found:  2540

                                                          source_path temp_folder_label  deltaT_label  T_plate_label series_id channel_raw channel_norm pressure_raw_label  pressure_corr_mpa      point_type                                                          pair_id                                        role  is_complete_pair                                                reference_zero_id
0      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-1.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-1.txt  EDA;pressure_calibration;joint_regression;              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-1.txt
1     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-10.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point  PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-10.txt  EDA;pressure_calibration;joint_regression;              True    PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-10.txt
2      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-2.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-2.txt  EDA;pressure_calibration;joint_regression;              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-2.txt
3      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-3.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-3.txt  EDA;pressure_calibration;joint_regression;              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-3.txt
4      PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0.5MPa-4.txt        DT0_T23_15           0.0             23        15         CH1            Y             0.5MPa                0.5  pressure_point   PAKA_AI\DT0_T23_15\15_CH2_X_SLOW\Switch_channel_2-0.5MPa-4.txt  EDA;pressure_calibration;joint_regression;              True     PAKA_AI\DT0_T23_15\15_CH1_Y_FAST\Switch_channel_1-0MPa-4.txt
...                                                               ...               ...           ...            ...       ...         ...          ...                ...                ...             ...                                                              ...                                         ...               ...                                                              ...
2535  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-5.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-5.txt                       EDA;joint_regression;              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-5.txt
2536  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-6.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-6.txt                       EDA;joint_regression;              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-6.txt
2537  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-7.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-7.txt                       EDA;joint_regression;              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-7.txt
2538  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-8.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-8.txt                       EDA;joint_regression;              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-8.txt
2539  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-9MPa-9.txt     DT45.7_T75_27          45.7             75        27         CH2            X               9MPa                9.0  pressure_point  PAKA_AI\DT45.7_T75_27\27_CH1_Y_FAST\Switch_channel_1-9MPa-9.txt                       EDA;joint_regression;              True  PAKA_AI\DT45.7_T75_27\27_CH2_X_SLOW\Switch_channel_2-0MPa-9.txt

[2540 rows x 14 columns]

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2540 entries, 0 to 2539
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   source_path         2540 non-null   str
 1   temp_folder_label   2540 non-null   str
 2   deltaT_label        2540 non-null   float64
 3   T_plate_label       2540 non-null   int64
 4   series_id           2540 non-null   str
 5   channel_raw         2540 non-null   str
 6   channel_norm        2540 non-null   str
 7   pressure_raw_label  2540 non-null   str
 8   pressure_corr_mpa   2540 non-null   float64
 9   point_type          2540 non-null   str
 10  pair_id             2540 non-null   str
 11  role                2540 non-null   str
 12  is_complete_pair    2540 non-null   bool
 13  reference_zero_id   2360 non-null   str
dtypes: bool(1), float64(2), int64(1), str(10)
memory usage: 260.6 KB

In [3]:
df.isnull().sum()

source_path             0
temp_folder_label       0
deltaT_label            0
T_plate_label           0
series_id               0
channel_raw             0
channel_norm            0
pressure_raw_label      0
pressure_corr_mpa       0
point_type              0
pair_id                 0
role                    0
is_complete_pair        0
reference_zero_id     180
dtype: int64

In [4]:
df["deltaT_label"].unique()

array([ 0. , 16.2, 20.5, 24.7, 27.4, 33. , 37.5, 41.8, 45.7])

In [5]:
df["T_plate_label"].unique()

array([23, 42, 45, 50, 55, 60, 65, 70, 75])

In [6]:
df["channel_norm"].unique()

<StringArray>
['Y', 'X']
Length: 2, dtype: str

In [7]:
df["pressure_corr_mpa"].unique()

array([ 0.5,  0. , 10. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,
        9. ,  0.1,  0.2])

In [8]:
df["role"].unique()

<StringArray>
[                 'EDA;pressure_calibration;joint_regression;',
 'EDA;temp_calibration;pressure_calibration;joint_regression;',
                    'EDA;joint_regression;repeatability_test;',
                      'EDA;temp_calibration;joint_regression;',
                                       'EDA;joint_regression;']
Length: 5, dtype: str

In [9]:
df["point_type"].unique()

<StringArray>
['pressure_point', 'zero_start', 'zero_end']
Length: 3, dtype: str

In [10]:
df["is_complete_pair"].unique()

array([ True])

In [11]:
db = pd.read_csv("Output_files/training_dataset.csv")
db

      pressure    dT  Tp   y_signal  x_signal                                        role  low_quality  x_quality  x_quality_ref  y_quality  y_quality_ref
0          0.5   0.0  23  -1.140635  0.195342  EDA;pressure_calibration;joint_regression;        False   0.994875       0.995729   0.993451       1.000000
1          0.5   0.0  23  -1.103324  0.183002  EDA;pressure_calibration;joint_regression;        False   0.990319       0.995444   0.982346       0.998576
2          0.5   0.0  23  -1.132613  0.193438  EDA;pressure_calibration;joint_regression;        False   0.993736       0.997153   0.987472       0.999146
3          0.5   0.0  23  -1.120898  0.208898  EDA;pressure_calibration;joint_regression;        False   0.992312       0.997153   0.984339       0.999715
4          0.5   0.0  23  -1.115012  0.199869  EDA;pressure_calibration;joint_regression;        False   0.992597       0.995729   0.985478       0.999146
...        ...   ...  ..        ...       ...                                         ...          ...        ...            ...        ...            ...
1175       9.0  45.7  75 -17.393602  6.353061                       EDA;joint_regression;        False   0.989468       0.990037   1.000000       1.000000
1176       9.0  45.7  75 -17.392781  6.335698                       EDA;joint_regression;        False   0.989468       0.989752   1.000000       1.000000
1177       9.0  45.7  75 -17.387492  6.334266                       EDA;joint_regression;        False   0.989468       0.989752   1.000000       1.000000
1178       9.0  45.7  75 -17.357476  6.360441                       EDA;joint_regression;        False   0.989752       0.990037   1.000000       1.000000
1179       9.0  45.7  75 -17.375052  6.322131                       EDA;joint_regression;        False   0.989468       0.990037   1.000000       1.000000

[1180 rows x 11 columns]